# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AnimalHos' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
 pod 'Alamofire', '~> 5.5'
 pod 'AFNetworking', '~> 2.6'
 pod 'ORStackView', '~> 3.0'
 pod 'SwiftyJSON', '~> 4.0'
 pod 'KakaoSDK'
 post_install do |installer|
   installer.pods_project.targets.each do |target|
       target.build_configurations.each do |config|
         config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
       end
    end
  end
  # Pods for AnimalHos

end
